Repository MicrosoftDocs/msteams-docs, pull requests merged in 2019-10, with the labels that each got.

#1023 mm-send-receive-messages
  msteams-platform/bots/how-to/conversations/send-and-receive-messages.md
Labels: pending review

#1024 mm-send-proactive-messages
  msteams-platform/bots/how-to/conversations/send-proactive-messages.md
Labels: WIP

#1025 mm-add-authentication-to-your-teams-bot
  msteams-platform/bots/how-to/conversations/add-authentication-to-your-teams-bot.md
  msteams-platform/bots/media/auth-bot-app-service-in-group.png
  msteams-platform/bots/media/auth-bot-app-service.png
  msteams-platform/bots/media/auth-bot-channels-registration-group.PNG
  msteams-platform/bots/media/auth-bot-channels-registration.PNG
  msteams-platform/bots/media/auth-bot-connect-to-teams-channel.png
  msteams-platform/bots/media/auth-bot-connection-test-accept.PNG
  msteams-platform/bots/media/auth-bot-connection-test-token.PNG
  msteams-platform/bots/media/auth-bot-deployed-logout.PNG
  msteams-platform/bots/media/auth-bot-identity-connection-adv1.PNG
  msteams-platform/bots/media/auth-bot-login-deployed-token.PNG
  msteams-platform/bots/media/auth-bot-login-deployed.PNG
  msteams-platform/bots/media/auth-bot-login-emulator-token.png
  msteams-platform/bots/media/auth-bot-login-emulator.PNG
  msteams-platform/bots/media/auth-bot-ngrok-start.PNG
  msteams-platform/bots/media/auth-bot-teams-ngrok-testing.png
  msteams-platform/bots/media/auth-bot-teams-upload.png
Labels: pending review

#1039 SM-Channel-and-Group-chat
  msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md
Labels: pending review

#1056 ActivityUpdateAndDeleteBot
  msteams-platform/bots/how-to/conversations/update-and-delete-bot-messages.md
Labels: pending review

#1054 Subscribe to Conversation Events
  msteams-platform/bots/how-to/conversations/Media/AppStudio-BotName-one.png
  msteams-platform/bots/how-to/conversations/Media/AppStudio-Setup-a-bot-BotRegistrationName-FullScreen.png
  msteams-platform/bots/how-to/conversations/Media/AppStudio-Setup-a-bot-BotRegistrationName-dev-botframework-com.png
  msteams-platform/bots/how-to/conversations/Media/AppStudio-Setup-a-bot-BotRegistrationName.png
  msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md
Labels: pending review

#1046 create bot commands menu
  msteams-platform/bots/how-to/conversations/Media/AppStudio-CommandMenu-Add.png
  msteams-platform/bots/how-to/conversations/Media/AppStudio-NewCommandMenu.png
  msteams-platform/bots/how-to/conversations/Media/AppStudio.png
  msteams-platform/bots/how-to/conversations/Media/bot-menu-sample.png
  msteams-platform/bots/how-to/conversations/create-a-bot-commands-menu.md
Labels: pending review

#1041 mm-update send-proactive-messages.md
  msteams-platform/bots/how-to/conversations/send-proactive-messages.md
Labels: blocked

#1068 mm-update-add-authentication-to-your-teams-bot
  msteams-platform/bots/how-to/conversations/add-authentication-to-your-teams-bot.md
Labels: pending review

#1038 mm-teams-context
  msteams-platform/bots/how-to/conversations/Media/ngrok-cmd.png
  msteams-platform/bots/how-to/conversations/Media/teams-bot-roster-chat.PNG
  msteams-platform/bots/how-to/conversations/Media/teams-bot-roster-details.png
  msteams-platform/bots/how-to/conversations/Media/teams-bot-roster-map.png
  msteams-platform/bots/how-to/conversations/get-teams-context.md
Labels: pending review

#1067 mm-update-send-and-receive-messages
  msteams-platform/bots/how-to/conversations/send-and-receive-messages.md
Labels: pending review

#1079 mm-update-send-proactive-messages.md
  msteams-platform/bots/how-to/conversations/send-proactive-messages.md
Labels: pending review

#1076 Channel and Group Chat
  Desktop - Shortcut.lnk
  msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md
Labels: pending review

#1078 Create bot commands menu
  msteams-platform/bots/how-to/conversations/Media/App-Studio.png
  msteams-platform/bots/how-to/conversations/Media/AppStudio-NewCommandMenu.png
  msteams-platform/bots/how-to/conversations/create-a-bot-commands-menu.md
Labels: pending review

#1077 Update and Delete Bot Messages
  msteams-platform/bots/how-to/conversations/update-and-delete-bot-messages.md
Labels: pending review

#1059 mm-send-and-receive-files.md
  msteams-platform/assets/images/bots/bot-file-upload-permission-card.png
  msteams-platform/bots/how-to/conversations/send-and-receive-files.md
  msteams-platform/bots/how-to/conversations/send-proactive-messages.md
Labels: pending review

#1090 Subscribe to conversation events
  msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md
Labels: pending review

#1092 mm-send-and-receive-files
  msteams-platform/bots/how-to/conversations/send-and-receive-files.md
Labels: pending review

#1106 Add TS snippets to bots/how-to/get-teams-context.md
  msteams-platform/bots/how-to/get-teams-context.md
Labels: pending review

#1100 Update update-and-delete-bot-messages.md
  msteams-platform/bots/how-to/update-and-delete-bot-messages.md
Labels: pending review

#1108 Fix for loop TS logic in update/delete messages article
  msteams-platform/bots/how-to/update-and-delete-bot-messages.md
Labels: pending review

#1101 Update create-a-bot-commands-menu.md
  msteams-platform/bots/how-to/Media/AppStudio-CommandMenu-Add.png
  msteams-platform/bots/how-to/Media/AppStudio-NewCommandMenu.png
  msteams-platform/bots/how-to/Media/AppStudio.png
  msteams-platform/bots/how-to/Media/bot-menu-sample.png
  msteams-platform/bots/how-to/create-a-bot-commands-menu.md
Labels: WIP, pending review

#1103 mm-restructure-samples-js
  msteams-platform/bots/how-to/conversations/conversation-basics.md
  msteams-platform/bots/how-to/conversations/send-and-receive-files.md
  msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md
Labels: pending review
