Repository MicrosoftDocs/msteams-docs, pull requests merged in 2020-01, with the labels that each got.

#1181 mm-teams-python-conversation-basics
  msteams-platform/bots/how-to/conversations/conversation-basics.md
Labels: ready

#1183 mm-teams-python-proactive-messages
  .openpublishing.publish.config.json
  msteams-platform/bots/how-to/conversations/send-proactive-messages.md
Labels: blocked, ready

#1248 updated store detail page
  .markdownlint.json
  msteams-platform/assets/images/store-detail-page/AppIcon-01.png
  msteams-platform/assets/images/store-detail-page/AppIcon-02.png
  msteams-platform/assets/images/store-detail-page/AppIconOutline-01.png
  msteams-platform/assets/images/store-detail-page/AppIconOutline-02.png
  msteams-platform/assets/images/store-detail-page/AppName-01.png
  msteams-platform/assets/images/store-detail-page/AppName-02.png
  msteams-platform/assets/images/store-detail-page/LongDescription-01.png
  msteams-platform/assets/images/store-detail-page/LongDescription-02.png
  msteams-platform/assets/images/store-detail-page/Screenshot-01.png
  msteams-platform/assets/images/store-detail-page/ShortDescription-01.png
  msteams-platform/assets/images/store-detail-page/ShortDescription-02.png
  msteams-platform/concepts/deploy-and-publish/appsource/prepare/detail-page-checklist.md
Labels: doc-enhancement
