Repository MicrosoftDocs/msteams-docs, pull requests merged in 2020-09, with the labels that each got.

#1551 Add gcc guidance
  msteams-platform/assets/images/gcc-configure.png
  msteams-platform/concepts/deploy-and-publish/overview.md
Labels: approved-for-publication, documentation-complete

#1967 Update add-authentication to detail AAD V2
  msteams-platform/bots/how-to/authentication/add-authentication.md
Labels: pull request under review

#1838 add SaaS to your app
  msteams-platform/TOC.yml
  msteams-platform/concepts/deploy-and-publish/add-saas-offer.md
Labels: approved-for-publication
