Repository MicrosoftDocs/msteams-docs, pull requests merged in 2020-07, with the labels that each got.

#1806 add visitor management
  msteams-platform/assets/images/visitor-management-create-request.png
  msteams-platform/assets/images/visitor-management-notify-host.png
  msteams-platform/samples/app-templates.md
Labels: approved-for-publication

#1816 Fix link
  msteams-platform/tabs/design/tabs.md
Labels: approved-for-publication, reviewed-by-teams

#1803 Update overview.md
  msteams-platform/assets/images/3TierImage.png
  msteams-platform/concepts/deploy-and-publish/appsource/post-publish/application-certification.md
  msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md
Labels: awaiting-final-approval

#1760 Tabs SSO release docs
  msteams-platform/assets/images/tabs/tabs-sso-prompt.png
  msteams-platform/tabs/how-to/authentication/auth-aad-sso.md
Labels: approved-for-publication, awaiting-final-approval, documentation-complete

#1842 update schema add new properties
  msteams-platform/resources/schema/manifest-schema.md
Labels: approved-for-publication

#1778 Add toolkit docs PUBLISH ON 7/7
  msteams-platform/TOC.yml
  msteams-platform/toolkit/visual-studio-code-overview.md
  msteams-platform/toolkit/vs-overview.md
Labels: approved-for-publication

#1858 Update visual-studio-code-overview.md
  msteams-platform/toolkit/visual-studio-code-overview.md
Labels: approved-for-publication

#1828 add staff check-ins
  msteams-platform/assets/images/staff-check-ins-create.png
  msteams-platform/samples/app-templates.md
Labels: approved-for-publication, documentation-complete

#1854 add grow your skills template
  msteams-platform/assets/images/grow-your-skills-acquired-skills-view.png
  msteams-platform/assets/images/grow-your-skills-all-projects-view.png
  msteams-platform/samples/app-templates.md
Labels: approved-for-publication, documentation-complete

#1852 Add add great ideas template
  msteams-platform/assets/images/great-ideas-all-view.png
  msteams-platform/assets/images/great-ideas-digest-view.png
  msteams-platform/samples/app-templates.md
Labels: approved-for-publication, documentation-complete

#1871 Ojasvichoudhary patch 1
  msteams-platform/assets/images/messaging-extension/user-attribution-bots.png
  msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md
Labels: approved-for-publication

#1723 Documentation on building a Virtual Assistant for Teams
  msteams-platform/TOC.yml
  msteams-platform/assets/images/bots/virtual-assistant/book-a-room-skill.png
  msteams-platform/assets/images/bots/virtual-assistant/business-functions.png
  msteams-platform/assets/images/bots/virtual-assistant/high-level-diagram.png
  msteams-platform/assets/images/bots/virtual-assistant/overview.png
  msteams-platform/assets/images/bots/virtual-assistant/switch-skills-prompt.png
  msteams-platform/samples/virtual-assistant.md
Labels: approved-for-publication

#1902 Update native-device-permissions.md
  msteams-platform/assets/images/device-permissions.png
  msteams-platform/assets/images/tabs/mobile-device-permissions-screen.png
  msteams-platform/assets/images/tabs/mobile-device-permissions.png
  msteams-platform/tabs/how-to/native-device-permissions.md
Labels: approved-for-publication

#1896 Update test-resource-specific-consent.md
  msteams-platform/graph-api/rsc/test-resource-specific-consent.md
Labels: approved-for-publication

#1900 Review E-Prescriptions app template addition
  msteams-platform/assets/images/e-prescriptions-app-template-admin.PNG
  msteams-platform/assets/images/e-prescriptions-app-template.PNG
  msteams-platform/samples/app-templates.md
Labels: approved-for-publication
