Repository MicrosoftDocs/msteams-docs, pull requests merged in 2021-05, with the labels that each got.

#2710 [Teams][CreatedTogetherModedocument][1477618]
  msteams-platform/TOC.yml
  msteams-platform/apps-in-teams-meetings/SampleApp.zip
  msteams-platform/apps-in-teams-meetings/SampleScene.zip
  msteams-platform/apps-in-teams-meetings/create-apps-for-teams-meetings.md
  msteams-platform/apps-in-teams-meetings/teams-together-mode.md
  msteams-platform/assets/images/apps-in-meetings/PostMeeting.png
  msteams-platform/assets/images/apps-in-meetings/PreMeeting.png
  msteams-platform/assets/images/apps-in-meetings/PreMeetingTab.png
  msteams-platform/assets/images/apps-in-meetings/app-studio.png
  msteams-platform/assets/images/apps-in-meetings/build-a-scene.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-dialog-view.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-dialog.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-experience.png
  msteams-platform/assets/images/apps-in-meetings/in-scene-configuration.png
  msteams-platform/assets/images/apps-in-meetings/json-sample.png
  msteams-platform/assets/images/apps-in-meetings/launchtogethermode.png
  msteams-platform/assets/images/apps-in-meetings/role-based-scene.png
  msteams-platform/assets/images/apps-in-meetings/scene-added-to-app.png
  msteams-platform/assets/images/apps-in-meetings/scene-applied.png
  msteams-platform/assets/images/apps-in-meetings/scene-picker.png
  msteams-platform/assets/images/apps-in-meetings/scene-zip-file.png
  msteams-platform/whats-new.md
Labels: DO NOT MERGE

#3453 Updates .NET CLI instructions
  msteams-platform/get-started/first-app-blazor.md
Labels: approved-for-publication, documentation-complete

#3274 [Feature][Bots][1694836]
  msteams-platform/bots/how-to/conversations/Media/mobile-bot-menu-sample.png
  msteams-platform/bots/how-to/create-a-bot-commands-menu.md
Labels: blocked
