Repository MicrosoftDocs/msteams-docs, pull requests merged in 2021-06, with the labels that each got.

#3506 [teamsfx] Bug triage / corrections
  msteams-platform/TOC.yml
  msteams-platform/get-started/first-app-bot.md
  msteams-platform/get-started/first-app-react.md
  msteams-platform/toolkit/visual-studio-code-overview.md
  msteams-platform/toolkit/visual-studio-code-tab-sso.md
Labels: documentation-complete

#3237 [Feature][Bots-Uninstall event][1489398]
  msteams-platform/assets/images/bots/uninstallbot.png
  msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md
  msteams-platform/whats-new.md
Labels: awaiting-final-approval

#3696 Add shared meeting stage design guidelines
  msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md
  msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md
  msteams-platform/assets/images/apps-in-meetings/PostMeeting.png
  msteams-platform/assets/images/apps-in-meetings/PreMeeting.png
  msteams-platform/assets/images/apps-in-meetings/PreMeetingTab.png
  msteams-platform/assets/images/apps-in-meetings/app-studio.png
  msteams-platform/assets/images/apps-in-meetings/assign-spot.png
  msteams-platform/assets/images/apps-in-meetings/build-a-scene.png
  msteams-platform/assets/images/apps-in-meetings/create-together-mode-scene-flow.png
  msteams-platform/assets/images/apps-in-meetings/drag-and-drop-scene.png
  msteams-platform/assets/images/apps-in-meetings/image-alignment.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-dialog-layout-dont.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-dialog-view.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-dialog.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-experience.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-tab-anatomy.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-tab-theming-do.png
  msteams-platform/assets/images/apps-in-meetings/in-meeting-tab-theming-dont.png
  msteams-platform/assets/images/apps-in-meetings/in-scene-configuration.png
  msteams-platform/assets/images/apps-in-meetings/interaction-shared-stage-do.png
  msteams-platform/assets/images/apps-in-meetings/interaction-shared-stage-dont.png
  msteams-platform/assets/images/apps-in-meetings/json-sample.png
  msteams-platform/assets/images/apps-in-meetings/launchtogethermode.png
  msteams-platform/assets/images/apps-in-meetings/meeting-stage-no-side-panel-default.png
  msteams-platform/assets/images/apps-in-meetings/meeting-stage-no-side-panel-min.png
  msteams-platform/assets/images/apps-in-meetings/meeting-stage-no-side-panel.png
  msteams-platform/assets/images/apps-in-meetings/meeting-stage-with-side-panel.png
  msteams-platform/assets/images/apps-in-meetings/role-based-scene.png
  msteams-platform/assets/images/apps-in-meetings/scene-added-to-app.png
  msteams-platform/assets/images/apps-in-meetings/scene-applied.png
  msteams-platform/assets/images/apps-in-meetings/scene-design-studio.png
  msteams-platform/assets/images/apps-in-meetings/scene-picker.png
  msteams-platform/assets/images/apps-in-meetings/scene-zip-file.png
  msteams-platform/assets/images/apps-in-meetings/share_to_stage_during_meeting.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-anatomy.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-edit-review.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-quiz.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-responsiveness-do.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-responsiveness-dont.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-scroll-do.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-scroll-dont.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-theming-do.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-theming-dont.png
  msteams-platform/assets/images/apps-in-meetings/shared-meeting-stage-whiteboard.png
Labels: approved-for-publication

#3718 Update app structure mocks
  msteams-platform/assets/images/design-guidelines/app-structure-bots-desktop.png
  msteams-platform/assets/images/design-guidelines/app-structure-bots-mobile.png
  msteams-platform/assets/images/design-guidelines/app-structure-bots.png
  msteams-platform/assets/images/design-guidelines/app-structure-meeting-exetensions-desktop.png
  msteams-platform/assets/images/design-guidelines/app-structure-meeting-exetensions-mobile.png
  msteams-platform/assets/images/design-guidelines/app-structure-meeting-exetensions.png
  msteams-platform/assets/images/design-guidelines/app-structure-messaging-exetensions-desktop.png
  msteams-platform/assets/images/design-guidelines/app-structure-messaging-exetensions-mobile.png
  msteams-platform/assets/images/design-guidelines/app-structure-messaging-exetensions.png
  msteams-platform/assets/images/design-guidelines/app-structure-personal-apps-desktop.png
  msteams-platform/assets/images/design-guidelines/app-structure-personal-apps-mobile.png
  msteams-platform/assets/images/design-guidelines/app-structure-personal-apps.png
  msteams-platform/assets/images/design-guidelines/app-structure-tabs-desktop.png
  msteams-platform/assets/images/design-guidelines/app-structure-tabs-mobile.png
  msteams-platform/concepts/design/app-structure.md
Labels: documentation-complete
